#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &

bspc config border_width            1
bspc config window_gap              18
bspc config normal_border_color     \#282828
bspc config active_border_color     \#EBDBB2
bspc config focused_border_color    \#EBDBB2
bspc config split_ratio             0.52

if xrandr -q | grep 'DP-2 connected'; then
    xrandr --output eDP-1 --off
    xrandr --output DP-2 --primary --mode 3440x1440 --rotate normal
    bspc monitor DP-2 -d 1 2 3 4 5
    bspc monitor -g 3440x1440+0+0
else
    bspc monitor -d 1 2 3 4 5
fi


feh --bg-fill ~/Pictures/bg.jpeg 

$HOME/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr

